/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ReportService } from "../report.service";
import { ReportCreateInput } from "./ReportCreateInput";
import { Report } from "./Report";
import { ReportFindManyArgs } from "./ReportFindManyArgs";
import { ReportWhereUniqueInput } from "./ReportWhereUniqueInput";
import { ReportUpdateInput } from "./ReportUpdateInput";
import { AnalyticsDataFindManyArgs } from "../../analyticsData/base/AnalyticsDataFindManyArgs";
import { AnalyticsData } from "../../analyticsData/base/AnalyticsData";
import { AnalyticsDataWhereUniqueInput } from "../../analyticsData/base/AnalyticsDataWhereUniqueInput";

export class ReportControllerBase {
  constructor(protected readonly service: ReportService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Report })
  async createReport(@common.Body() data: ReportCreateInput): Promise<Report> {
    return await this.service.createReport({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        createdDate: true,
        title: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Report] })
  @ApiNestedQuery(ReportFindManyArgs)
  async reports(@common.Req() request: Request): Promise<Report[]> {
    const args = plainToClass(ReportFindManyArgs, request.query);
    return this.service.reports({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        createdDate: true,
        title: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Report })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async report(
    @common.Param() params: ReportWhereUniqueInput
  ): Promise<Report | null> {
    const result = await this.service.report({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        createdDate: true,
        title: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Report })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateReport(
    @common.Param() params: ReportWhereUniqueInput,
    @common.Body() data: ReportUpdateInput
  ): Promise<Report | null> {
    try {
      return await this.service.updateReport({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          createdDate: true,
          title: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Report })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteReport(
    @common.Param() params: ReportWhereUniqueInput
  ): Promise<Report | null> {
    try {
      return await this.service.deleteReport({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          createdDate: true,
          title: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/analyticsDataItems")
  @ApiNestedQuery(AnalyticsDataFindManyArgs)
  async findAnalyticsDataItems(
    @common.Req() request: Request,
    @common.Param() params: ReportWhereUniqueInput
  ): Promise<AnalyticsData[]> {
    const query = plainToClass(AnalyticsDataFindManyArgs, request.query);
    const results = await this.service.findAnalyticsDataItems(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        metricName: true,
        metricValue: true,
        recordedAt: true,

        report: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/analyticsDataItems")
  async connectAnalyticsDataItems(
    @common.Param() params: ReportWhereUniqueInput,
    @common.Body() body: AnalyticsDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      analyticsDataItems: {
        connect: body,
      },
    };
    await this.service.updateReport({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/analyticsDataItems")
  async updateAnalyticsDataItems(
    @common.Param() params: ReportWhereUniqueInput,
    @common.Body() body: AnalyticsDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      analyticsDataItems: {
        set: body,
      },
    };
    await this.service.updateReport({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/analyticsDataItems")
  async disconnectAnalyticsDataItems(
    @common.Param() params: ReportWhereUniqueInput,
    @common.Body() body: AnalyticsDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      analyticsDataItems: {
        disconnect: body,
      },
    };
    await this.service.updateReport({
      where: params,
      data,
      select: { id: true },
    });
  }
}
